---
title: "Early Substance Use and Hard Drug Behaviors: A Predictive Analysis"
author: "Jade Chen, Jessica Luo, Heidi Lantz, Nazia Edroos"
format: html
---

# Dataset
This dataset is sourced from [FiveThirtyEight’s repository](https://github.com/rudeboybert/fivethirtyeight/tree/master/data-raw/drug-use-by-age), which is derived from from the [2013 National Survey on Drug Use and Health](https://doi.org/10.3886/ICPSR35509.v3), conducted by the United States Department of Health and Human Services, Substance Abuse and Mental Health Services Administration (SAMHSA), Center for Behavioral Health Statistics and Quality.

The dataset covers self-reported drug use trends across 17 age groups in the United States, examining 13 different substances.

**Disclaimer:** This analysis is distinct from the FiveThirtyEight article [How Baby Boomers Get High](https://fivethirtyeight.com/features/how-baby-boomers-get-high/). Our study focuses on a different research question, examining whether adolescent alcohol and marijuana use (ages 12-19) can predict hard substance use in early adulthood (ages 20-29) using predictive modeling.

## Predictive Question

**Can patterns of alcohol and marijuana use in early adolescence predict hard substance use behaviors in early adulthood (ages 20-29)?**

- Independent Variables (Ages 12-19)
    - `alcohol-use`
    - `alcohol-frequency`
    - `marijuana-use`
    - `marijuana-frequency`

- Dependent Variables (Ages 20-29)
    - `cocaine-use`
    - `cocaine-frequency`
    - `heroin-use`
    - `heroin-frequency`
    - `meth-use`
    - `meth-frequency`
    

## Data Summary

TODO: add some EDA

```{r, echo = FALSE}
#load("data/data.rda") # Load dataset

#data <- da35509.0001 # Assigning loaded data to 'data'

#summary(data) # Display summary statistics
```

## Data Cleaning

1. Handle missing values by removing rows with excessive missing data or imputing reasonable values.
2. Check format of variable and transform as needed.
3. Check for outliers in age-related variables.
4. Standardize or normalize predictor variables as needed.

## Analysis

Use linear regression, blah blah blah. Perform correlation analysis to identify significant predictors before modeling. Evaluate model performance using accuracy or RMSE.